[build]
  publish = "build"
  command = "bundle exec middleman build"

[context.production]
  command = "bundle exec middleman build && cache restore"

[context.deploy-preview]
  command = "bundle exec middleman build && cache restore"

[context.branch-deploy]
  command = "bundle exec middleman build && cache restore"
